name: Update Pull Request Description
description: Easily update a pull requests description

inputs:
  body:
    description: The new pull request description
    required: true
  token:
    description: A GitHub access token
    required: true
  jiraBaseUrl:
    description: The base jira url for the project example https://example.atlassian.net/browse
    required: true

runs:
  using: node12
  main: dist/index.js

branding:
  icon: git-pull-request
  color: red
